# https://docs.travis-ci.com/user/build-stages
# https://kean.github.io/post/ci-for-frameworks
# https://github.com/mxcl/PromiseKit/blob/master/.travis.yml

# All targets, including watchOS, are build in Carthage compile step.

os: osx
osx_image: xcode10.3
language: swift

stages:
  - name: compile
  - name: test

jobs:
  include:

    # Compile

    - stage: compile
      name: Carthage
      script: travis_retry carthage build --no-skip-current --configuration Release

    - stage: compile
      name: CocoaPods (pod lib lint)
      cache: cocoapods
      install: gem install cocoapods # Since Travis is not always on the latest version…
      script: travis_retry pod lib lint

    # Test

    - &test
      stage: test
      name: Xcode 10.3 (macOS)
      xcode_project: SwiftyNSException.xcodeproj
      xcode_scheme: SwiftyNSException-macOS
      xcode_destination: 'platform=macOS'
      after_success: bash <(curl -s https://codecov.io/bash)

    - <<: *test
      name: Xcode 10.3 (iOS)
      xcode_scheme: SwiftyNSException-iOS
      xcode_destination: 'platform=iOS Simulator,OS=12.2,name=iPhone SE'

    - <<: *test
      name: Xcode 10.3 (tvOS)
      xcode_scheme: SwiftyNSException-tvOS
      xcode_destination: 'platform=tvOS Simulator,OS=12.2,name=Apple TV'
