language: objective-c
osx_image: xcode8.3

env:
   global:
   - PROJECT="SwiftyNSException.xcodeproj"
   - IOS_SCHEME="SwiftyNSException-iOS"
   - MACOS_SCHEME="SwiftyNSException-macOS"
   - TVOS_SCHEME="SwiftyNSException-tvOS"
   - WATCHOS_SCHEME="SwiftyNSException-watchOS"

   - IOS_SDK=iphonesimulator10.3
   - MACOS_SDK=macosx10.12
   - TVOS_SDK=appletvsimulator10.2
   - WATCHOS_SDK=watchsimulator3.2

   matrix:
   - DESTINATION="OS=8.1,name=iPhone 4s"                    SDK="$IOS_SDK"     SCHEME="$IOS_SCHEME"     RUN_TESTS="YES" POD_LINT="YES"
   - DESTINATION="OS=8.2,name=iPhone 5"                     SDK="$IOS_SDK"     SCHEME="$IOS_SCHEME"     RUN_TESTS="YES" POD_LINT="NO"
   - DESTINATION="OS=8.3,name=iPhone 5s"                    SDK="$IOS_SDK"     SCHEME="$IOS_SCHEME"     RUN_TESTS="YES" POD_LINT="NO"
   - DESTINATION="OS=8.4,name=iPhone 6"                     SDK="$IOS_SDK"     SCHEME="$IOS_SCHEME"     RUN_TESTS="YES" POD_LINT="NO"
           
   - DESTINATION="OS=9.0,name=iPhone 6 Plus"                SDK="$IOS_SDK"     SCHEME="$IOS_SCHEME"     RUN_TESTS="YES" POD_LINT="NO"
   - DESTINATION="OS=9.1,name=iPhone 6s"                    SDK="$IOS_SDK"     SCHEME="$IOS_SCHEME"     RUN_TESTS="YES" POD_LINT="NO"
   - DESTINATION="OS=9.2,name=iPhone 6s Plus"               SDK="$IOS_SDK"     SCHEME="$IOS_SCHEME"     RUN_TESTS="YES" POD_LINT="NO"
   - DESTINATION="OS=9.3,name=iPad Pro (12.9-inch)"         SDK="$IOS_SDK"     SCHEME="$IOS_SCHEME"     RUN_TESTS="YES" POD_LINT="NO"
           
   - DESTINATION="OS=10.0,name=iPhone 6s"                   SDK="$IOS_SDK"     SCHEME="$IOS_SCHEME"     RUN_TESTS="YES" POD_LINT="NO"
   - DESTINATION="OS=10.1,name=iPhone 7"                    SDK="$IOS_SDK"     SCHEME="$IOS_SCHEME"     RUN_TESTS="YES" POD_LINT="NO"
   - DESTINATION="OS=10.2,name=iPad Air 2"                  SDK="$IOS_SDK"     SCHEME="$IOS_SCHEME"     RUN_TESTS="YES" POD_LINT="NO"
   - DESTINATION="OS=10.3,name=iPhone 7"                    SDK="$IOS_SDK"     SCHEME="$IOS_SCHEME"     RUN_TESTS="YES" POD_LINT="NO"
    
   - DESTINATION="arch=x86_64"                              SDK="$MACOS_SDK"   SCHEME="$MACOS_SCHEME"   RUN_TESTS="YES" POD_LINT="NO"
   
   - DESTINATION="OS=9.0,name=Apple TV 1080p"               SDK="$TVOS_SDK"    SCHEME="$TVOS_SCHEME"    RUN_TESTS="YES" POD_LINT="NO"
   - DESTINATION="OS=10.0,name=Apple TV 1080p"              SDK="$TVOS_SDK"    SCHEME="$TVOS_SCHEME"    RUN_TESTS="YES" POD_LINT="NO"

   - DESTINATION="OS=2.0,name=Apple Watch - 38mm"           SDK="$WATCHOS_SDK" SCHEME="$WATCHOS_SCHEME" RUN_TESTS="NO"  POD_LINT="NO"
   - DESTINATION="OS=3.2,name=Apple Watch Series 2 - 42mm"  SDK="$WATCHOS_SDK" SCHEME="$WATCHOS_SCHEME" RUN_TESTS="NO"  POD_LINT="NO"

script:
- set -o pipefail

- if [ $POD_LINT == "YES" ]; then
      pod lib lint;
  fi

- if [ $RUN_TESTS == "YES" ]; then
      xcodebuild analyze test -project "$PROJECT" -scheme "$SCHEME" -sdk "$SDK" -destination "$DESTINATION" -configuration Debug ONLY_ACTIVE_ARCH=NO CODE_SIGNING_REQUIRED=NO | xcpretty -c;
  else
      xcodebuild build analyze -project "$PROJECT" -scheme "$SCHEME" -sdk "$SDK" -destination "$DESTINATION" -configuration Debug ONLY_ACTIVE_ARCH=NO CODE_SIGNING_REQUIRED=NO | xcpretty -c;
  fi

after_success:
   - bash <(curl -s https://codecov.io/bash)